function denoised_signal = denoise_bandpass(signal, fs)
% DENOISE_BANDPASS  Bandpass (0.5-40 Hz) + notch (powerline) filtering.
%   denoised_signal = denoise_bandpass(signal, fs)
%
% CHANGE 'notch_freq' below to 60 if your mains power is 60 Hz (e.g. US,
% which is what MIT-BIH itself was recorded under), or 50 if 50 Hz mains.

    notch_freq = 60; % Hz - change if your context needs it

    bp = designfilt('bandpassiir', ...
        'FilterOrder', 4, ...
        'HalfPowerFrequency1', 0.5, ...
        'HalfPowerFrequency2', 40, ...
        'SampleRate', fs);

    notch = designfilt('bandstopiir', ...
        'FilterOrder', 2, ...
        'HalfPowerFrequency1', notch_freq - 2, ...
        'HalfPowerFrequency2', notch_freq + 2, ...
        'SampleRate', fs);

    stage1 = filtfilt(bp, signal);
    denoised_signal = filtfilt(notch, stage1);
end
